### ISSUE TITLE
Unit Tests not correctly associated with PR Checks

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform-github-oidc-provider#4]
After raising the following PR: https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/3

You can see in the checks that the Go Terratest does not seem to be associated with the pull: https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/3/checks

However, in the actions you can see that the PR _does_ trigger the correct action: https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/actions/runs/2775044838

**Comment by SimonPPledger** [comment]
this is now working
